#############################################################################
# Makefile for building: game_manocha
# Generated by qmake (2.01a) (Qt 4.8.1) on: Wed May 1 23:13:05 2013
# Project:  game_manocha.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile game_manocha.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = bullet.cpp \
		environment.cpp \
		gamemenu.cpp \
		gameview.cpp \
		globals.cpp \
		main.cpp \
		mainwindow.cpp \
		object.cpp \
		player.cpp \
		zombie.cpp moc_gamemenu.cpp \
		moc_gameview.cpp \
		moc_mainwindow.cpp
OBJECTS       = bullet.o \
		environment.o \
		gamemenu.o \
		gameview.o \
		globals.o \
		main.o \
		mainwindow.o \
		object.o \
		player.o \
		zombie.o \
		moc_gamemenu.o \
		moc_gameview.o \
		moc_mainwindow.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		game_manocha.pro
QMAKE_TARGET  = game_manocha
DESTDIR       = 
TARGET        = game_manocha

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: game_manocha.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile game_manocha.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile game_manocha.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/game_manocha1.0.0 || $(MKDIR) .tmp/game_manocha1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/game_manocha1.0.0/ && $(COPY_FILE) --parents bullet.h environment.h gamemenu.h gameview.h globals.h mainwindow.h object.h player.h zombie.h .tmp/game_manocha1.0.0/ && $(COPY_FILE) --parents bullet.cpp environment.cpp gamemenu.cpp gameview.cpp globals.cpp main.cpp mainwindow.cpp object.cpp player.cpp zombie.cpp .tmp/game_manocha1.0.0/ && (cd `dirname .tmp/game_manocha1.0.0` && $(TAR) game_manocha1.0.0.tar game_manocha1.0.0 && $(COMPRESS) game_manocha1.0.0.tar) && $(MOVE) `dirname .tmp/game_manocha1.0.0`/game_manocha1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/game_manocha1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_gamemenu.cpp moc_gameview.cpp moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_gamemenu.cpp moc_gameview.cpp moc_mainwindow.cpp
moc_gamemenu.cpp: gamemenu.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) gamemenu.h -o moc_gamemenu.cpp

moc_gameview.cpp: object.h \
		player.h \
		bullet.h \
		zombie.h \
		gameview.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) gameview.h -o moc_gameview.cpp

moc_mainwindow.cpp: gameview.h \
		object.h \
		player.h \
		bullet.h \
		zombie.h \
		gamemenu.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

bullet.o: bullet.cpp bullet.h \
		object.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bullet.o bullet.cpp

environment.o: environment.cpp environment.h \
		object.h \
		globals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o environment.o environment.cpp

gamemenu.o: gamemenu.cpp mainwindow.h \
		gameview.h \
		object.h \
		player.h \
		bullet.h \
		zombie.h \
		gamemenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gamemenu.o gamemenu.cpp

gameview.o: gameview.cpp mainwindow.h \
		gameview.h \
		object.h \
		player.h \
		bullet.h \
		zombie.h \
		gamemenu.h \
		globals.h \
		environment.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gameview.o gameview.cpp

globals.o: globals.cpp globals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o globals.o globals.cpp

main.o: main.cpp mainwindow.h \
		gameview.h \
		object.h \
		player.h \
		bullet.h \
		zombie.h \
		gamemenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		gameview.h \
		object.h \
		player.h \
		bullet.h \
		zombie.h \
		gamemenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

object.o: object.cpp object.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o object.o object.cpp

player.o: player.cpp gameview.h \
		object.h \
		player.h \
		bullet.h \
		zombie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o player.o player.cpp

zombie.o: zombie.cpp zombie.h \
		object.h \
		player.h \
		bullet.h \
		globals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zombie.o zombie.cpp

moc_gamemenu.o: moc_gamemenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gamemenu.o moc_gamemenu.cpp

moc_gameview.o: moc_gameview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gameview.o moc_gameview.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

